databases:
  - name: jandroman
    databaseName: jandroman
    user: jandroman

services:
  - type: web
    name: jandroman
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jandroman.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jandroman
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4